=== chriswareham/superfly/src/site/components.dtd
<!--
   Superfly Components version 1.0 DTD

   Copyright (c) 2015 Chris Wareham,
   All Rights Reserved.

   This DTD is identified by the PUBLIC and SYSTEM identifiers:

   PUBLIC "-//Superfly//DTD Components 1.0//EN"
   SYSTEM "http://www.chriswareham.net/DTD/components.dtd"
-->

<!-- ========================== Entities =========================== -->

<!ENTITY % Instantiation "(immediate | demand)">

<!-- ========================== Elements =========================== -->

<!ELEMENT components (include*, component*)>

<!ELEMENT include EMPTY>
<!ATTLIST include
  path CDATA #REQUIRED
  >

<!ELEMENT component (constructorarg*, (property | list | map)*)>
<!ATTLIST component
  id            CDATA           #REQUIRED
  class         CDATA           #REQUIRED
  instantiation %Instantiation; "immediate"
  startup       CDATA           #IMPLIED
  shutdown      CDATA           #IMPLIED
  >

<!ELEMENT constructorarg EMPTY>
<!ATTLIST constructorarg
  class CDATA #REQUIRED
  refid CDATA #IMPLIED
  value CDATA #IMPLIED
  >

<!ELEMENT property EMPTY>
<!ATTLIST property
  name  CDATA #REQUIRED
  refid CDATA #IMPLIED
  value CDATA #IMPLIED
  >

<!ELEMENT list (item*)>
<!ATTLIST list
  name  CDATA #REQUIRED
  >

<!ELEMENT item EMPTY>
<!ATTLIST item
  refid CDATA #IMPLIED
  value CDATA #IMPLIED
  >

<!ELEMENT map (entry*)>
<!ATTLIST map
  name  CDATA #REQUIRED
  >

<!ELEMENT entry EMPTY>
<!ATTLIST entry
  key   CDATA #REQUIRED
  refid CDATA #IMPLIED
  value CDATA #IMPLIED
  >

<!-- =============================================================== -->

=== chriswareham/superfly/src/test/resources/testcomponents.xml
<?xml version='1.0'?>
<!DOCTYPE components PUBLIC "-//Superfly//DTD Components 1.0//EN" "http://www.chriswareham.net/DTD/components.dtd">
<components>

    <include path="/testincludecomponents.xml"/>

    <component id="testComponent" class="net.chriswareham.di.TestComponentImpl" instantiation="immediate"/>

    <component id="testPrototypeComponent" class="net.chriswareham.di.TestComponentImpl" instantiation="demand"/>

    <component id="prototypeComponent" class="net.chriswareham.di.TestComponentImpl" instantiation="demand"/>

    <component id="component" class="net.chriswareham.di.TestComponentImpl" startup="startup" shutdown="shutdown">
        <property name="managedName" value="TestComponentImpl:key=value"/>
        <property name="reference" refid="testComponent"/>
        <property name="prototypeReference" refid="testPrototypeComponent"/>
        <property name="stringProperty" value="string"/>
        <property name="booleanProperty" value="true"/>
        <property name="intProperty" value="1"/>
        <property name="longProperty" value="10"/>
        <property name="floatProperty" value="100.0"/>
        <property name="doubleProperty" value="1000.0"/>
        <list name="referenceCollection">
            <item refid="testComponent"/>
            <item refid="testPrototypeComponent"/>
        </list>
        <list name="stringCollection">
            <item value="one"/>
            <item value="two"/>
        </list>
        <list name="booleanCollection">
            <item value="true"/>
            <item value="false"/>
        </list>
        <list name="intCollection">
            <item value="1"/>
            <item value="2"/>
        </list>
        <list name="longCollection">
            <item value="10"/>
            <item value="20"/>
        </list>
        <list name="floatCollection">
            <item value="100.0"/>
            <item value="200.0"/>
        </list>
        <list name="doubleCollection">
            <item value="1000.0"/>
            <item value="2000.0"/>
        </list>
        <map name="referenceMap">
            <entry key="one" refid="testComponent"/>
            <entry key="two" refid="testPrototypeComponent"/>
        </map>
        <map name="stringMap">
            <entry key="one" value="one"/>
            <entry key="two" value="two"/>
        </map>
        <map name="booleanMap">
            <entry key="true" value="false"/>
            <entry key="false" value="true"/>
        </map>
        <map name="intMap">
            <entry key="1" value="3"/>
            <entry key="2" value="4"/>
        </map>
        <map name="longMap">
            <entry key="10" value="30"/>
            <entry key="20" value="40"/>
        </map>
        <map name="floatMap">
            <entry key="100.0" value="300.0"/>
            <entry key="200.0" value="400.0"/>
        </map>
        <map name="doubleMap">
            <entry key="1000.0" value="3000.0"/>
            <entry key="2000.0" value="4000.0"/>
        </map>
    </component>

</components>

=== chriswareham/superfly/src/main/resources/components.xml
<?xml version='1.0'?>
<!DOCTYPE components PUBLIC "-//Superfly//DTD Components 1.0//EN" "http://www.chriswareham.net/DTD/components.dtd">
<components>

    <component id="dataSource" class="org.postgresql.ds.PGSimpleDataSource">
        <property name="serverName" value="@DATABASE_SERVER@"/>
        <property name="portNumber" value="@DATABASE_PORT@"/>
        <property name="databaseName" value="@DATABASE_NAME@"/>
        <property name="user" value="testuser"/>
        <property name="password" value="t3stp4ssw0rd"/>
    </component>

    <component id="dataSourceWrapper" class="net.chriswareham.da.DataSourceImpl">
        <property name="dataSource" refid="dataSource"/>
        <property name="minIdle" value="0"/>
        <property name="maxIdle" value="25"/>
        <property name="maxActive" value="-1"/>
        <property name="maxWait" value="-1"/>
    </component>

    <component id="queryService" class="net.chriswareham.da.QueryServiceImpl">
        <property name="dataSource" refid="dataSourceWrapper"/>
    </component>

    <component id="serialiser" class="net.chriswareham.da.SerialiserServiceImpl">
        <property name="key" value="XXX"/>
    </component>

</components>

=== chriswareham/superfly/src/site/components.xml
<?xml version='1.0'?>
<!DOCTYPE components PUBLIC "-//Superfly//DTD Components 1.0//EN" "http://www.chriswareham.net/DTD/components.dtd">
<components>

    <component id="dataSource" class="org.postgresql.ds.PGSimpleDataSource">
        <property name="serverName" value="localhost"/>
        <property name="portNumber" value="5432"/>
        <property name="databaseName" value="test"/>
        <property name="user" value="username"/>
        <property name="password" value="p4ssw0rd"/>
    </component>

    <component id="dataSourceWrapper" class="net.chriswareham.da.DataSourceImpl">
        <property name="dataSource" refid="dataSource"/>
        <property name="minIdle" value="0"/>
        <property name="maxIdle" value="25"/>
        <property name="maxActive" value="-1"/>
        <property name="maxWait" value="-1"/>
    </component>

    <component id="queryService" class="net.chriswareham.da.QueryServiceImpl">
        <property name="dataSource" refid="dataSourceWrapper"/>
    </component>

    <component id="serialiser" class="net.chriswareham.da.SerialiserServiceImpl">
        <property name="key" value="s3cr3t"/>
    </component>

</components>

=== chriswareham/superfly/src/main/resources/events_components.xml
<?xml version='1.0'?>
<!DOCTYPE components PUBLIC "-//Superfly//DTD Components 1.0//EN" "http://www.chriswareham.net/DTD/components.dtd">
<components>

    <component id="connectionFactory" class="org.apache.activemq.ActiveMQConnectionFactory">
        <property name="brokerURL" value="tcp://localhost:61616"/>
    </component>

    <component id="pooledConnectionFactory" class="org.apache.activemq.pool.PooledConnectionFactory" shutdown="stop">
        <property name="connectionFactory" refid="connectionFactory"/>
    </component>

    <component id="destination" class="org.apache.activemq.command.ActiveMQQueue">
        <constructorarg class="java.lang.String" value="test"/>
    </component>

    <component id="events" class="net.chriswareham.events.EventsJmsImpl">
        <property name="connectionFactory" refid="pooledConnectionFactory"/>
        <map name="topic">
            <entry key="test" refid="destination"/>
        </map>
    </component>

</components>
